# Generated by Django 6.0.4 on 2026-04-28 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessgenai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessidea',
            old_name='full_analysis',
            new_name='analysis',
        ),
        migrations.AddField(
            model_name='businessidea',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessidea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
